import {
  AlertCircle,
  CircleUser,
  Square,
  Image,
  LineChart,
  ChevronsUpDown,
  Menu as MenuIcon,
  Sliders,
  TableIcon,
  MessageSquare,
  Calendar,
  CheckSquare,
  TextCursorInput,
  ChevronRight,
  FileText,
  ToggleLeft,
  Maximize2,
  RectangleHorizontal,
  MenuSquare,
  List,
  Command,
  AlertTriangle,
  Bell,
  AlignCenter,
  CornerDownRight,
  RadioIcon,
  Dices,
  PanelLeft,
  Asterisk,
  Grip,
  ScrollText,
  LayoutGrid,
  MousePointer,
  GripVertical,
  Layers,
  Search,
  FormInput,
  ArrowDownUp,
  RotateCcw,
  SlidersHorizontal,
  Loader2,
  SunMoon,
  Check,
  Mail,
  ShieldAlert,
  Sparkles,
  PanelRightOpen,
  User,
  Loader,
  Palette,
  Wand,
  Flower2,
  Hourglass,
  PartyPopper,
  Download,
  BookOpen,
  TimerIcon,
  PaintBucket,
  Navigation2Icon,
  GraduationCapIcon,
  GitPullRequestDraft,
  ChevronsLeftRightEllipsisIcon,
  RefreshCcw,
  CalendarDays,
  LucideGitCommitVertical,
  BoxesIcon,
  BabyIcon,
  Dock,
  PanelBottomIcon,
  TextCursor,
  OrbitIcon,
  BedDoubleIcon,
  WavesIcon,
  MenuSquareIcon,
  Navigation2OffIcon,
  TypeIcon,
  LucideTreePalm,
  GalleryThumbnailsIcon,
  LucideAlignHorizontalDistributeStart,
  ImageIcon,
  ImageDownIcon,
  ArrowUpCircle,
  DonutIcon,
  LucideSnail,
  MousePointer2,
  SlidersIcon,
  SparklesIcon,
  SlidersVertical,
  Navigation2,
  LoaderCircleIcon,
  CurlyBracesIcon,
  LucideFileImage,
  ScrollIcon,
  Terminal,
  BarChart,
  ParenthesesIcon,
  Globe,
  RectangleVerticalIcon,
  TriangleDashed,
  Text,
  ListChecks,
  BetweenHorizontalEnd,
  VideoIcon,
  TorusIcon,
  ShieldMinus,
  LucideReceiptPoundSterling,
  TheaterIcon,
  MoveDiagonal2,
  TriangleAlert,
  ArrowUpAzIcon,
  Code2Icon,
  AppleIcon,
  PlaneTakeoff,
  Grid2X2Check,
  ChartLineIcon,
  BadgeMinus,
  BellElectric,
  SlidersVerticalIcon,
  Copy,
  Plus,
  CheckCircle2,
} from "lucide-react";
import { FaGrinBeam } from "react-icons/fa";

// Helper function to convert name to lowercase with hyphens
// Modified to handle "new" badge display without double hyphenation in the formatted name itself.
const formatName = (name) => name.toLowerCase().replace(/\s+/g, "-");

// Group components by category with their icons
export const uiComponents = [
  { name: formatName("Alert"), icon: AlertCircle },
  { name: formatName("Alert Dialog"), icon: AlertTriangle },
  { name: formatName("Animated Number Stepper"), icon: SlidersHorizontal },
  { name: formatName("Avatar"), icon: CircleUser },
  { name: formatName("Badge"), icon: Square }, // Added newComp for Badge
  { name: formatName("Button"), icon: Square },
  { name: formatName("Card"), icon: Square },
  { name: formatName("Carousel"), icon: Image },
  { name: formatName("Chart"), icon: LineChart },
  { name: formatName("Collapsible"), icon: ChevronsUpDown },
  // { name: formatName("Confetti Button"), icon: PartyPopper },
  { name: formatName("Context Menu"), icon: MenuIcon },
  { name: formatName("Dialog"), icon: MessageSquare },
  { name: formatName("Drawer"), icon: PanelRightOpen },
  { name: formatName("Dropdown Menu"), icon: ChevronRight },
  { name: formatName("Hover Card"), icon: MousePointer },
  { name: formatName("Popover"), icon: Asterisk },
  { name: formatName("Progress"), icon: Sliders },
  { name: formatName("Sheet"), icon: PanelLeft },
  { name: formatName("Skeleton"), icon: LayoutGrid },
  { name: formatName("Table"), icon: TableIcon },
  { name: formatName("Toast"), icon: Bell },
  { name: formatName("Tooltip"), icon: MessageSquare },
];

export const formComponents = [
  { name: formatName("Calendar"), icon: Calendar },
  { name: formatName("Checkbox"), icon: CheckSquare },
  // { name: formatName("Combobox"), icon: ChevronsUpDown },
  { name: formatName("Command"), icon: Command },
  { name: formatName("Form"), icon: FormInput },
  { name: formatName("Input"), icon: TextCursorInput },
  { name: formatName("Input OTP"), icon: Square },
  { name: formatName("Label"), icon: CornerDownRight },
  { name: formatName("Radio Group"), icon: RadioIcon },
  { name: formatName("Select"), icon: ChevronRight },
  { name: formatName("Slider"), icon: SlidersHorizontal },
  { name: formatName("Switch"), icon: ToggleLeft },
  { name: formatName("Textarea"), icon: FileText },
  { name: formatName("Toggle"), icon: ToggleLeft },
  { name: formatName("Toggle Group"), icon: ToggleLeft },
];

export const layoutComponents = [
  { name: formatName("Accordion"), icon: ChevronsUpDown },
  { name: formatName("Aspect Ratio"), icon: Maximize2 },
  { name: formatName("Resizable"), icon: GripVertical },
  { name: formatName("Scroll Area"), icon: ScrollText },
  { name: formatName("Separator"), icon: RectangleHorizontal },
  { name: formatName("Tabs"), icon: MenuSquare },
];

export const navigationComponents = [
  { name: formatName("Breadcrumb"), icon: List },
  { id: "nav-command", name: formatName("Command"), icon: Command },
  // { name: formatName("Menubar"), icon: MenuIcon },
  { name: formatName("Navigation Menu"), icon: MenuIcon },
  { name: formatName("Pagination"), icon: ArrowDownUp },
  { name: formatName("Sidebar"), icon: MenuSquare },
];

export const utilityComponents = [
  { name: formatName("Draggable Reorder List"), icon: GripVertical },
  { name: formatName("Slide To Confirm"), icon: CheckCircle2 },
  { name: formatName("Expandable Search Bar"), icon: Search },
  { name: formatName("Expandable Speed Dial"), icon: Plus },
  { name: formatName("Animated Copy Button"), icon: Copy },
  { name: formatName("Cool Theme Toggle"), icon: SunMoon },
  { name: formatName("Toggle Theme"), icon: SunMoon },
];

export const backgroundComponents = [
  { name: formatName("Animated Wave"), icon: WavesIcon },
  { name: formatName("Animated Bubble Particles"), icon: OrbitIcon },
  { name: formatName("Aurora Shader"), icon: ArrowUpAzIcon },
  { name: formatName("Beam Grid Background"), icon: BadgeMinus },
  { name: formatName("Dot Grid Background"), icon: DonutIcon, newComp: true },
  { name: formatName("Fall Beam Background"), icon: Grid2X2Check },
  { name: formatName("Grid Dot Backgrounds"), icon: DonutIcon },
  { name: formatName("Gradient Background"), icon: DonutIcon },
  { name: formatName("Hell Background"), icon: DonutIcon },
  { name: formatName("Interactive Grid Background"), icon: DonutIcon },

  {
    name: formatName("Particles Background"),
    icon: ParenthesesIcon,
  },
  { name: formatName("Rays Background"), icon: DonutIcon },
  { name: formatName("Reflect Background"), icon: DonutIcon },
  { name: formatName("Smokey Background"), icon: DonutIcon },
  { name: formatName("Liquid Surface"), icon: WavesIcon },
  { name: formatName("Shader Background"), icon: DonutIcon },
  { name: formatName("Sparkle Particles"), icon: SparklesIcon },
  { name: formatName("Stripes Background"), icon: DonutIcon },
  { name: formatName("Wave Background"), icon: WavesIcon },
];

export const animatedButton = [
  { name: formatName("Border Beam"), icon: BoxesIcon },
  { name: formatName("Confetti Button"), icon: PartyPopper },
  { name: formatName("Gradient Button"), icon: GitPullRequestDraft },
  { name: formatName("Magnetic Button"), icon: MousePointer2 },
  {
    name: formatName("Ripple Button"),
    icon: LucideReceiptPoundSterling,

  },
  { name: formatName("Shine Button"), icon: ShieldMinus },
  { name: formatName("Trial Button"), icon: TriangleAlert },
];

export const ThreeDElements = [
  // { name: formatName("Clickable Key 3d"), icon: SlidersVertical },
  { name: formatName("3d Image Ring"), icon: SlidersVertical },
  { name: formatName("Ascii Wave"), icon: WavesIcon, newComp: true },
  { name: formatName("3d Image Carousel"), icon: CurlyBracesIcon },
  { name: formatName("3D Carousel"), icon: CurlyBracesIcon },
  { name: formatName("3D Image Slider"), icon: CurlyBracesIcon, newComp: true },
  {
    name: formatName("3D Hover Gallery"),
    icon: LucideAlignHorizontalDistributeStart,
  },
  { name: formatName("3D Marquee"), icon: ImageDownIcon },
  { name: formatName("3D Model Viewer"), icon: MoveDiagonal2 },
  { name: formatName("3D Perspective Card"), icon: TheaterIcon },
  { name: formatName("3D Scroll Trigger"), icon: TheaterIcon },
  { name: formatName("3D Slider"), icon: SlidersVerticalIcon },
  { name: formatName("Angled Slider"), icon: SlidersVerticalIcon },
  { name: formatName("Beam Circle"), icon: FaGrinBeam },
  { name: formatName("Chain Carousel"), icon: ChartLineIcon },
  { name: formatName("Infinite Drift"), icon: TheaterIcon, newComp: true },
  { name: formatName("Infinite WebGL Scroll"), icon: LayoutGrid, newComp: true },
  { name: formatName("Plasma Globe"), icon: PlaneTakeoff },

  { name: formatName("Scroll Carousel"), icon: TheaterIcon },
  { name: formatName("Sparkle Navbar"), icon: TheaterIcon },
  // { name: formatName("3D Image Gallery"), icon: GalleryThumbnailsIcon },
];

export const animatedCursor = [
  { name: formatName("Canvas Confetti Cursor"), icon: BedDoubleIcon },
  // { name: formatName("Magic Cursor"), icon: TextCursor },
  { name: formatName("Particle Orbit Effect"), icon: OrbitIcon },
  { name: formatName("Smokey Cursor"), icon: MousePointer },
  { name: formatName("Smooth Cursor"), icon: MousePointer2 },
];

export const animatedText = [
  { name: formatName("Aurora Text Effect"), icon: Wand },
  {
    name: formatName("Scroll Reveal"),
    icon: LucideAlignHorizontalDistributeStart,
  },
  { name: formatName("Shiny Text"), icon: SparklesIcon },
  { name: formatName("Text Scroll Marquee"), icon: Text },
  { name: formatName("Typewriter Input"), icon: TypeIcon },
  { name: formatName("Typing Text"), icon: TypeIcon },
  { name: formatName("Rolling Text 3D"), icon: TypeIcon },
  { name: formatName("3D Scroll Paragraph"), icon: TypeIcon },
  { name: formatName("Video Text"), icon: VideoIcon }, // Added newComp for Video Text
  { name: formatName("Looping Words"), icon: TypeIcon, newComp: true },
];

// Animated components category
export const animatedComponents = [
  // { name: formatName("Ai Prompt"), icon: Code2Icon },
  { name: formatName("Animated Notification"), icon: Navigation2OffIcon },
  // { name: formatName("Animated Range Input"), icon: Navigation2OffIcon },
  { name: formatName("Bento Grid"), icon: BetweenHorizontalEnd },

  {
    name: formatName("Code Hover Cards"),
    icon: LucideAlignHorizontalDistributeStart,
  },
  { name: formatName("Count Up"), icon: LucideGitCommitVertical },
  { name: formatName("Dock"), icon: Dock },
  { name: formatName("Drag Order List"), icon: ListChecks },
  { name: formatName("Dynamic Island"), icon: PanelBottomIcon, newComp: true },
  { name: formatName("Dynamic Navigation"), icon: Navigation2Icon },
  { name: formatName("Electro Border"), icon: BellElectric },
  { name: formatName("Glass Folder"), icon: Sparkles },
  { name: formatName("Globe"), icon: Globe },
  { name: formatName("Glowing Cards"), icon: Sparkles },
  { name: formatName("Hamburger Menu Overlay"), icon: MenuSquareIcon },
  {
    name: formatName("Image Reveal"),
    icon: RectangleVerticalIcon,
  },
  {
    name: formatName("Image Trail Effect"),
    icon: TriangleDashed,
  },
  { name: formatName("Interactive Card"), icon: SlidersIcon },
  { name: formatName("Interactive Gradient Card"), icon: PaintBucket },
  { name: formatName("Iphone16 Pro"), icon: AppleIcon },
  { name: formatName("Lens"), icon: LucideSnail },
  { name: formatName("Magic Card"), icon: Sparkles },
  { name: formatName("Magic Loader"), icon: LoaderCircleIcon },
  { name: formatName("Morphing Navigation"), icon: Navigation2OffIcon },
  { name: formatName("Orbit Card"), icon: OrbitIcon },
  { name: formatName("Password Strength Indicator"), icon: ShieldAlert },
  { name: formatName("Scroll Cards"), icon: ScrollIcon, newComp: true },
  { name: formatName("Scroll Paragraph"), icon: ScrollIcon },
  { name: formatName("Scroll List"), icon: ScrollIcon },
  { name: formatName("Scroll Stack"), icon: ScrollIcon, newComp: true },
  { name: formatName("Scroll Timeline"), icon: TimerIcon },
  { name: formatName("Seasonal Hover Cards"), icon: Sparkles },
  { name: formatName("Sliding Cards"), icon: SlidersIcon, newComp: true },
  { name: formatName("Sliding Logo Marquee"), icon: SlidersIcon },
  { name: formatName("Stack List"), icon: SlidersIcon },
  { name: formatName("Team Carousel"), icon: LucideTreePalm },
  { name: formatName("Terminal Card"), icon: Terminal },
  { name: formatName("Top Loader"), icon: Loader },
  { name: formatName("Top Sticky Bar"), icon: BarChart },
  { name: formatName("Trusted Users"), icon: TorusIcon },
  { name: formatName("Ripple Loader"), icon: Loader },
  { name: formatName("Woofy Hover Image"), icon: LucideFileImage },

];

export const blocksComponents = [
  { id: "analytics02", name: "Analytics 02", icon: LineChart, isBlock: true },
  { id: "3dblock01", name: "3D Carousel", icon: BoxesIcon, isBlock: true },
  { id: "hero01", name: "Creative Agency Hero", icon: PanelRightOpen, isBlock: true },
];

// New getting started categories
export const gettingStartedCategories = [
  {
    id: formatName("Introduction"),
    name: formatName("Introduction"),
    icon: BookOpen,
    description: "Learn about Lightspeed UI and its key features",
  },
  {
    id: formatName("Installation"),
    name: formatName("Installation"),
    icon: Download,
    description: "How to install dependencies and structure your app",
  },
  {
    id: formatName("MCP Server"),
    name: formatName("MCP Server"),
    icon: Terminal,
    description: "Connect Lightswind UI to AI agents via Model Context Protocol",

  },
  {
    id: formatName("Lightswind Extension"),
    name: formatName("Lightswind Extension"),
    icon: Wand,
    description: "Install and use the Lightswind AI browser extension",

  },
];

export type ComponentItem = {
  name: string;
  icon: any;
  newComp?: boolean;
  description?: string;
  id?: string;
};

export const allComponentCategories: { title: string; components: ComponentItem[] }[] = [
  { title: "Get Started", components: gettingStartedCategories },
  { title: "Blocks", components: blocksComponents },
  { title: "Utilities", components: utilityComponents },
  { title: "3D Elements", components: ThreeDElements },
  { title: "Background", components: backgroundComponents },
  { title: "Button", components: animatedButton },
  { title: "Components", components: animatedComponents },
  { title: "Cursor", components: animatedCursor },
  { title: "Text", components: animatedText },
  { title: "UI Elements", components: uiComponents },
  { title: "Form Controls", components: formComponents },
  { title: "Layout", components: layoutComponents },
  { title: "Navigation", components: navigationComponents },
];
