export const versionCategories = [

    {
        title: "Core Components",
        components: [
            "alerts",
            "tabs",
            "buttons",
            "buttons-groups",
            "breadcrumbs",
            "clipboards",
            "dropdowns",
            "date-pickers",
            "loaders",
            "marquees",
            "menus",
            "paginations",
            "progress-bars",
            "skeletons",
            "sticky-bars",
            "toasts",
            "tooltips",
        ],
    },
    {
        title: "Application Ui",
        components: [
            "cards",
            "gallerys",
            "forms",
            "forms-buttons",
            "footers",
            "navbars",
            "sidebars",
            "sections",
        ],
    },
    {
        title: "Application Page",
        components: [
            "appointment-forms",
            "ai-page",
            "blogs-page",
            "business-page",
            "checkout-page",
            "hero-sections",
            "portfolio-page",
            "q&a-section",
            "ecommerce-cards",
            "ecommerce-page",
            "subscription-page",
        ],
    },
];
